global:
receivers:
  - name: apy-webhook
    webhook_configs:
      - url: "http://host.docker.internal:3000/webhook"
route:
  # group_wait: 10s
  # group_interval: 5m
  group_by: ['alertname']
  receiver: apy-webhook
  # # receiver: ycap-webhook
  # repeat_interval: 3h
  
  # routes: 
  #   - receiver: apy-webhook
  #     match_re:
  #       app: apy