global:
  scrape_interval: 15s


# Rules and alerts are read from the specified file(s)
rule_files:
  - rules.yml


alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
  
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: apy_monitor_job
    static_configs:
      - targets: ["192.168.0.105:8090"]