groups:
- name: apy
  rules:
  - alert: Notification
    expr: abs(delta(APY_CHANGE_GAGUE[10m])) > 10
    for: 0m
    labels:
      app: apy
      severity: warning
    annotations:
      summary: change in APY 
      description: "Change in APY of value\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"